### ISSUE TITLE
报告疑难问题：按照步骤，提示非法心跳，这是成功还是失败了？

### ISSUE THREAD

**Issue by diaosimiao** [giuem/bilive#1]
node index.js
显示
Status: failed
Time: 省略
Response: {"code":-403,"msg":"非法心跳","data":[1492814199,1492814102]}
UserInfo: 省略（名字头像等级硬币等都有显示）
显示非法心跳，请问您，这是成功了还是失败了？
感谢项目，谢谢~

**Comment by giuem** [comment]
两次心跳间隔小于 6 分钟就会显示非法心跳

**Comment by diaosimiao** [comment]
@giuem 明白了，要设置定时器6分钟以上，谢谢大佬及时回复。

**Comment by diaosimiao** [comment]
明白了，谢谢大佬及时回复。
